stages:
  - test

offline_tests:
  stage: test
  image: node:${NODE_VERSION}-bookworm-slim
  parallel:
    matrix:
      - NODE_VERSION: ['22', '24']
  script:
    - npm ci --ignore-scripts --no-audit --no-fund
    - npm run check
    - npm test
    - npm audit --audit-level=low
